### ISSUE TITLE
パラメータの調整

### ISSUE THREAD

**Issue by YH-koko** [SawadaAoi/UniBoooom_repository#172]
値の調整お願いします。
下記の値は変更済の数値データなので上書きしてください。

●fade.cpp
const TTriType<int> FRAME_FADE_MAX(100, 60, 70);			//フェードにかけるフレーム数	x:アウト, y:ストップ, z:イン
const int FRAME_OUT_PATTERN_2_FIN(80);	

●GameParameter.h
・プレイヤー
const float HAMMER_INTERVAL_TIME	= 0.1f * 60;	// ハンマー振り間隔

・ 敵キャラ 
 共通
const int	MAX_SLIME_NUM = 20;		// スライムの最大生成数
const float MOVE_DISTANCE_PLAYER = 16.0f;	// プレイヤー追跡移動に切り替える距離

const int ENEMY_CREATE_INTERVAL = int(1.0f * 60);								// 生成間隔
const int CREATE_DISTANCE = 18;									// プレイヤーからどれくらい離れた距離に生成するか

・スライム同士の反射の減算値
const float LEAVE_DISTANCE = 29.0f;					// これ以上離れたら対角線上に移動する

・カメラ
const TDiType<int> INIT_FRAME_WEAK = { 99, 100 };					//弱振動のフレーム数	x:横, y:縦
const TDiType<int> INIT_FRAME_STRONG = { 99, 100 };					//強振動のフレーム数	x:横, y:縦
const std::vector<float> TABLE_AMPITUDE_WEAK[E_DIRECT_VIBRATE_MAX] = {
	{ -1.1f, 1.1f },	//横弱振幅
	{ 0.3f, 0.1f, 0.0f, 0.1f, 0.3f },	//縦弱振幅
};
const std::vector<float> TABLE_AMPITUDE_STRONG[E_DIRECT_VIBRATE_MAX] = {
	{ -1.1f, 1.1f },	//横強振幅
	{ -5.0f, -2.0f, 0.0f, 2.0f, 5.0f  },	//縦強振幅
};

**Comment by YH-koko** [comment]
すいません。ヒットストップも数値調整してください。
const int FRAME_STOP_SOFT = 10;		//ストップ：軽　のフレーム数	// 現在使用している物

**Comment by YH-koko** [comment]
爆発の揺れ調整(2023年12月1日)

//カメラ

const TDiType<int> INIT_FRAME_WEAK = { 110, 110 };					//弱振動のフレーム数	x:横, y:縦
const TDiType<int> INIT_FRAME_STRONG = { 110, 110 };					//強振動のフレーム数	x:横, y:縦
const TDiType<float> CHANGE_RATE_AMPLITUDE_WEAK{ 0.99f, 0.99f };	//強振幅変化率	1を超えると増加方向、下回ると減少方向	x:横, y:縦
const TDiType<float> CHANGE_RATE_AMPLITUDE_STRONG{ 0.99f, 0.99f };	//強振幅変化率	1を超えると増加方向、下回ると減少方向	x:横, y:縦
///<summary>振幅の確率：弱///<para>合計が1になる必要はない</para>
///</summary>
const std::vector<double> PROBABILITY_AMPITUDE_WEAK[E_DIRECT_VIBRATE_MAX] = {
	{ 0.1, 0.3, 0.5, 0.3, 0.1  },	//横弱振動
	{ 0.1, 0.3, 0.5, 0.3, 0.1  },	//縦弱振動
};
///<summary>
///<see cref="PROBABILITY_AMPITUDE_WEAK">←上記定数</see>のテーブル
///<para>順番がそのまま対応しており、同じ数ないと機能しない(添削は自由)</para>
///<para>各値は振幅の大きさを表す</para>
///</summary>
const std::vector<float> TABLE_AMPITUDE_WEAK[E_DIRECT_VIBRATE_MAX] = {
	{ -0.05f, -0.025f, 0.0f, 0.025f, 0.05f  },	//横弱振幅
	{ -0.05f, -0.025f, 0.0f, 0.025f, 0.05f  },	//縦弱振幅
};
///<summary>振幅の確率：強
///<para>合計が1になる必要はない</para>
///</summary>
const std::vector<double> PROBABILITY_AMPITUDE_STRONG[E_DIRECT_VIBRATE_MAX] = {
	{  0.1, 0.3, 0.5, 0.3, 0.1  },	//横弱振動
	{ 0.1, 0.3, 0.5, 0.3, 0.1  },	//縦弱振動
};
///<summary>
///<see cref="PROBABILITY_AMPITUDE_STRONG">←上記定数</see>のテーブル
///<para>順番がそのまま対応しており、同じ数ないと機能しない(添削は自由)</para>
///<para>各値は振幅の大きさを表す</para>
///</summary>
const std::vector<float> TABLE_AMPITUDE_STRONG[E_DIRECT_VIBRATE_MAX] = {
	{ -0.25f, -0.15f, 0.0f, 0.15f, 0.25f  },	//横強振幅
	{ -2.5f, -1.5f, 0.0f, 1.5f, 2.5f },	//縦強振幅
};

**Comment by YH-koko** [comment]
// ヒットストップ =========================================================
const int FRAME_STOP_SOFT = 2;		//ストップ：軽　のフレーム数	// 現在使用している物
const int FRAME_STOP_NORMAL = 5;	//ストップ：中　のフレーム数

**Comment by TakagiShunsuke** [comment]
振動・ヒットストップ対応しました。

**Comment by YH-koko** [comment]
最新画面振動パラメーター

const TDiType<int> INIT_FRAME_WEAK = { 125, 125 };					//弱振動のフレーム数	x:横, y:縦
const TDiType<int> INIT_FRAME_STRONG = { 150, 150 };				//強振動のフレーム数	x:横, y:縦
const TDiType<float> CHANGE_RATE_AMPLITUDE_WEAK{ 0.99f, 0.99f };	//強振幅変化率	1を超えると増加方向、下回ると減少方向	x:横, y:縦
const TDiType<float> CHANGE_RATE_AMPLITUDE_STRONG{ 0.97f, 0.97f };	//強振幅変化率	1を超えると増加方向、下回ると減少方向	x:横, y:縦
///<summary>振幅の確率：弱
///<para>合計が1になる必要はない</para>
///</summary>
const std::vector<double> PROBABILITY_AMPITUDE_WEAK[E_DIRECT_VIBRATE_MAX] = {
	{ 0.1, 0.3, 0.5, 0.3, 0.1 }, //横弱振動
	{ 0.1, 0.3, 0.5, 0.3, 0.1 }, //縦弱振動
};
///<summary>
///<see cref="PROBABILITY_AMPITUDE_WEAK">←上記定数</see>のテーブル
///<para>順番がそのまま対応しており、同じ数ないと機能しない(添削は自由)</para>
///<para>各値は振幅の大きさを表す</para>
///</summary>
const std::vector<float> TABLE_AMPITUDE_WEAK[E_DIRECT_VIBRATE_MAX] = {
	{ -0.05f, -0.025f, 0.0f, 0.025f, 0.05f }, //横弱振幅
	{ -0.05f, -0.025f, 0.0f, 0.025f, 0.05f }, //縦弱振幅
};
///<summary>振幅の確率：強
///<para>合計が1になる必要はない</para>
///</summary>
const std::vector<double> PROBABILITY_AMPITUDE_STRONG[E_DIRECT_VIBRATE_MAX] = {
	{ 0.1, 0.3, 0.5, 0.3, 0.1 },	//横強振動
	{ 0.1, 0.3, 0.5, 0.3, 0.1 },	//縦強振動
};
///<summary>
///<see cref="PROBABILITY_AMPITUDE_STRONG">←上記定数</see>のテーブル
///<para>順番がそのまま対応しており、同じ数ないと機能しない(添削は自由)</para>
///<para>各値は振幅の大きさを表す</para>
///</summary>
const std::vector<float> TABLE_AMPITUDE_STRONG[E_DIRECT_VIBRATE_MAX] = {
	{ -0.1f, -0.05f, 0.0f, 0.05f, 0.1f }, //横強振幅
	{ -1.25f, -0.7f, 0.0f, 0.7f, 1.25f }, //縦強振幅
};
