### ISSUE TITLE
オブジェクトの親クラスを作る

### ISSUE THREAD

**Issue by SawadaAoi** [SawadaAoi/UniBoooom_repository#51]
各オブジェクトが持つ以下3つの変数は、どのオブジェクトも持つことになるだろうから共通化すべき？
・座標(TPos3d<Pos3d>)
・当たり判定(Sphere)

**Comment by TakagiShunsuke** [comment]
これはプロトタイプ終了後でいいのですが、Transform3dというファイルをインクルードし、tagTransform3dという構造体型を使用するとワールド行列変換など共通化できるようにしましたので良ければご使用ください。
また、CSphereInfoのクラスとしての機能がないので構造体のみ抜き出して定義し、tagTransform3dを継承すれば、一つの型にまとめることができます。
